SCORE website theme
eclipse-score/eclipse-score.github.io pull request #3
Opened 2024-12-05 07:28 UTC by danwos

This PR adds the pyData-sphinx-theme to the documentation and sets some colors and visual highlights. The goal is to have pleasant landing page.

**Status**: This PR is in **DRAFT** mode, to discuss certain details.

### ToDo
* [ ] Get bazel build running, as it does not copy some important pydata-sphinx-theme to the sandbox
* [ ] Reduce video size (it's 5 MB currently, should be 1 MB)
* [ ] Merge "contribute" content to https://github.com/eclipse-score/score/blob/main/CONTRIBUTION.md (or vice versa)
* [ ] Transform heavy-text content to landing page/focused content (Another PR)

### Showcase
https://github.com/user-attachments/assets/ebda8da8-d56f-48eb-bf81-083732bcd179

### Build
Currently possible only without bazel and via own python venv:
```
# Install dependencies
python -m venv .venv
source .venv/bin/activate  # linux
pip install -r docs/requirements.txt

# Run documentation build
sphinx-build docs/ docs/_build/html

# Open the build
firefox docs/_build/html/index.hml
```

Changes:

* Uses pyData Sphinx theme
* Changes default theme colors
* Adds Score title video
* Add Contribute page for basic doc setup/infos

2024-12-06 11:03 UTC, qor-lb requested changes
Thank you very much for the proposal, I like it a lot! 

As discussed, we would like to include some minor changes in the presentation
- Removing the video on the lading page
- Enabling page specific sidebars
- Merging the color codes from the contribution guide with the main contribution guide in the score repo
- Inclusion of additional main tab "Get Involved" (see below)
- Rollout of theme to main score repo with a "fixed" top level navigation bar across the two locations


## Content for "Get Involved"
```rst
How to get in contact with SCORE
********************************

If you want to get into contact with SCORE, these are your primary entry points: 

- Project Mailing List: score-dev@eclipse.org
- Architectural Discussion & Ideas: `#score-project-open-channel <https://sdvworkinggroup.slack.com/archives/C083Z4VL90B>`
- General Information / Alignment regarding SCORE as a basis for distributions & products: contact one of the project leads of SCORE https://projects.eclipse.org/projects/automotive.score/who

The technical HOWTO regarding involvement into SCORE is described here: 
https://github.com/eclipse-score/score/blob/main/CONTRIBUTION.md

How to get involved into SCORE
******************************

The _only_ way to influence SCORE is TO CONTRIBUTE. Everybody can contribute – SCORE is open.

Active Contributions to the SCORE project are the basis for getting involved. The SCORE Project works according to 
the Eclipse Project Handbook and has named and elected project leads and committers (see https://projects.eclipse.org/projects/automotive.score/who). 
Direction of the SCORE project is discussed and decided in the project lead circle, technical direction is created and prediscussed in the tech 
lead circle. Meeting notes are transparent via the SCORE github organization. (see https://github.com/orgs/eclipse-score/discussions)

We aim to build a safety ready full stack architecture, where components fit to each other in 
automotive grade Software Quality and performance. To achieve this, we follow a strict feature roadmap and architecture
and a rigid software development process (publicly available in the SCORE Project Handbook starting end of 2024). 

Contributions to the SCORE project must therefore follow the technical direction of the project and the SCORE 
architecture. All work in SCORE will therefore follow a "Contribution Request" Process. Features on the roadmap of 
SCORE are defined, Contribution Requests create the basis for individual contributions from within the SCORE 
project and also from the outside.

You can make proposals for new features or architectural building blocks besides the active contribution requests. 
Those will not by default be part of the next release of SCORE, because the SCORE release roadmap will strictly 
comply with the contribution request structure. 
We plan to have the initial contribution request structure available in the SCORE GitHub until Q1 / 2025.

We plan to incorporate a staging area for such contributions, but
in the initial phase of the SCORE project (until end of 2025) the focus will be primarily on building a valid 1.0 
release. Feel free to reach out via the communication channels above.

If you think about your contribution to SCORE, the Contribution Request overview
is the best place to start (available on https://github.com/eclipse-score/score/issues starting Q1 / 2025)

Based on successful code contributions to the SCORE roadmap, further steps in involvement (like becoming a committer) 
will be handled according to the rules of the Eclipse Foundation Project Handbook. We value real code based 
collaboration and will judge new potential contributors and committers mainly on the validity of their work. Active 
and sustaining contributions are the basis for the ability to shape SCORE.

Making active code contributions via the contribution request process described in the Project Handbook. The 
project handbook will be available on the SCORE website until end of 2024.
```

2024-12-06 11:05 UTC, qor-lb commented
@ltekieli / @nradakovic could you please support @danwos to resolve the bazel integration issues related to the sphinx theme? @danwos could you please specify the problem you are facing?

2024-12-06 14:05 UTC, danwos commented on docs/conf.py
Right sidebar is done, it's just a config in the rst file to hide this element per page:
`:html_theme.sidebar_secondary.remove:`

Left sidebar gets automatically added for subfolders, which may have multiple files.
Example:
```rst
.. toctree::
   :hidden:

   get_involved    # will show NO left sidebar, as it is only one file
   my_topic/index  # will show left sidebar, as the folder could contain more.
```

So, with the chosen pydata_sphinx_theme, the root navigation starts at the top navbar, and it is decided whether the page shows the left sidebar on the second-level navigation.

2024-12-06 14:42 UTC, danwos commented
Thanks for all the feedback.
All points are implemented as requested.

Only missing is the role out to the score main documentation project, as this needs to be done in a separate PR on the specific repository.

Thanks @ltekieli for the help with bazel, doc-build is working now.

2024-12-06 14:43 UTC, danwos commented
Ohh and the Commit-Checker has forced me to provide an issue-id.
I used `Issue-ref: see #007`, as I don't have any issue. I hope this is fine :)

2024-12-06 14:49 UTC, danwos commented
Thanks, I have integrated it and just pushed it. Let's see, if it works.

2024-12-06 14:49 UTC, ltekieli commented
> Ohh and the Commit-Checker has forced me to provide an issue-id. I used `Issue-ref: see #007`, as I don't have any issue. I hope this is fine :)

@qor-lb would be better to provide an issue for it.

2024-12-06 14:59 UTC, danwos commented
Updated the commit message to use issue #4.
@qor-lb: Thanks for the issue.

2024-12-09 07:57 UTC, qor-lb approved these changes
@danwos thank you very much! 
Should we leave this PR open until the theme is also rolled out to the main repo or close it right away?

2024-12-09 08:59 UTC, danwos commented
The PR for the main repo is ready :)
https://github.com/eclipse-score/score/pull/48

2024-12-09 10:46 UTC, merged